### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ghubcoder** [usedbytes/picowota#2]
Hello, thanks for this! 

When following the instructions I get:

```
picowota/tcp_comm.c:534:28: error: 'MAX_NARG' undeclared (first use in this function)
```

Have I missed something simple?

Edit: works if you change the lines referenced above to be:

```c
        for (i = 0; i < n_cmds; i++) {
                assert(cmds[i]->nargs <= COMM_MAX_NARG);
                assert(cmds[i]->resp_nargs <= COMM_MAX_NARG);
        }
```

I also had to modify line 640 in main.c to be a while loop as my Pico fails to connect sometimes........

```c
	while (cyw43_arch_wifi_connect_timeout_ms(wifi_ssid, wifi_pass, CYW43_AUTH_WPA2_AES_PSK, 30000))
	{
		DBG_PRINTF("failed to connect.\n");
		sleep_ms(500);
	}
```

**Comment by usedbytes** [comment]
Hey, thanks for the report!

Not sure how I missed that typo, I'll update later

**Comment by ghubcoder** [comment]
Great thanks, I will close this.

**Comment by usedbytes** [comment]
It was building OK for me I guess because I wasn't doing debug builds, and so the `assert()`s weren't getting evaluated. Were you doing a debug build?

Anyway fixed now - thanks for the report.

**Comment by ghubcoder** [comment]
Yep was a debug build. Thanks for sorting!
